[project]
name = "one-billion-row-challenge"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "polars>=1.31.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "ruff>=0.12.0",
]
